config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

    root to: 'home#index'

    get '/terms' => 'pages#terms'
    get '/about' => 'pages#about'

    resources :users

    resources :articles do
      resources :comments
    end

    namespace :admin do
      resources :users, only: %i[index create edit update destroy]
    end

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
  end
end

app/views/shared/_add_comment.html.erb
<%= turbo_frame_tag @article.comments.new do%>
<div class="btn btn-outline-secondary btn-sm">
  <%= link_to 'Add comment', new_article_comment_path(@article), :class => "btn", :style => "--bs-btn-padding-y: .1rem; --bs-btn-padding-x: .15rem; --bs-btn-font-size: .65rem;"%>
</div>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>   <!-- поставить '&' когда будет ошибка -->
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
       <li><p5><%= msg %></p5></li> 
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="container-fluid">
    <div class="row">
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"><%= t('home.home') %></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li> 
            <a class="nav-link active" href="/terms">Terms</a>
          </li>
          <li>
            <a class="nav-link active" href="/about">About</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Menu
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/">Articles</a></li>
              <li><a class="dropdown-item" href="<%= new_article_path(@article)%>">Add new article</a></li>
            </ul>
            </li class="nav-item">
        </ul>
        <ul class="navbar-nav navbar-right">
          <li class="dropdown">
            <%= link_to '#', class: "nav-link dropdown-toggle text-white", data: {"bs-toggle": 'dropdown'} do %>
              <%= tag.div '', class: "flag #{I18n.locale}-flag" %>
              <%= t(locale) %>
            <% end %>
            <ul class="dropdown-menu">
              <% I18n.available_locales.each do |locale| %>
              <li>
                <% if I18n.locale == locale %>
                  <%= tag.span t(locale), class: "dropdown-item" %>
                <% else %>
                  <%= link_to t(locale), root_path(locale: locale), class: "dropdown-item" %>
                <% end %>
              </li>
              <% end %>
            </ul>
          </li>
        </ul>
        <ul class="navbar-nav navbar-right">
          <%if user_signed_in?%>
          <div class="fixed-right p-2 text-light">
            Welcome, <%= link_to "#{current_user.username}", edit_user_registration_path, class: 'home_links', style: 'color: white' %>
          </div>
          <div class="btn btn-light btn-sm">
            <%= link_to 'Sign Out', destroy_user_session_path, class: "btn btn-sm"%>
            </div>
          <%else%>
          <div class="btn btn-light btn-sm">
            <%= link_to 'Log In', new_user_session_path, class: "btn btn-sm"%>
          </div>
          <%end%>
        </ul>
      </div>
    </div>
    </nav>
    </div>
  </div>
</header>

app/views/shared/_last_comment.html.erb
<p><%=@comment.body%></p>
<p6> Published <b><%= "#{User.find(@comment.user_id).username}" %></b>, in <%= "#{@comment.created_at.strftime("%Y-%m-%d %H:%M")}" %></p6>
<hr>
<%= render 'shared/add_comment' %>